# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44a94dfc3523447dfa2df8dfc6f117265f47a7514510862f52c3b3335b5d731f371ea534277eeab683b1e33f28e65757a781816dc91a5bdc3eb0cd53e0ff4821

test:
  secret_key_base: 4ecfce9c7715b3cf07152e56c5293401efa5c058bb6bf6c8197c9a6031f6cad592b473f2fa3f0ba6ac98a07355eab7e893418d53fd0752a3c5a42df24f2978cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
